env vars

diff --git a/.github/workflows/packer.yml b/.github/workflows/packer.yml
--- a/.github/workflows/packer.yml
+++ b/.github/workflows/packer.yml
@@ -5,6 +5,12 @@ on:
     branches: [main]
 
 env:
+  DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
+  DB_USERNAME: ${{ secrets.DB_USERNAME }}
+  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+  NEW_TEMPLATE_NAME: ${{ secrets.NEW_TEMPLATE_NAME }}
+  KMS_KEY_SELF_LINK: ${{ secrets.KMS_KEY_SELF_LINK }}
+  GCP_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
   PROJECT_ID: csye6225csye
   INSTANCE_GROUP_NAME: webapp-group-manager
   REGION: us-east1
@@ -57,78 +63,63 @@ jobs:
         echo "Image Family Name: $IMAGE_FAMILY"
         echo "::set-output name=IMAGE_FAMILY::$IMAGE_FAMILY"
 
-    - name: Create Image Name
-      id: create_image_name
-      run: |
-        IMAGE_NAME="gcp-${{ steps.create_timestamp.outputs.TIMESTAMP }}"
-        echo "Image Name: $IMAGE_NAME"
-        echo "::set-output name=IMAGE_NAME::$IMAGE_NAME"
-
     - name: Build machine image with Packer
       id: image_build
       run: |
         cd packer
         packer init .
-        packer build -var 'artifact_path=${{ github.workspace }}/target/cloud-app-0.0.1-SNAPSHOT.jar' -var 'project_id=csye6225csye' -var 'zone=us-east1-b' cent.pkr.hcl > image_packer.txt
-        image_name=$(grep 'Image creation complete' image_packer.txt | awk '{print $4}')
-        echo "::set-output name=image_name::$image_name"
-        
-      env:
-        # NEW_IMAGE_NAME: webapp-image-${{ github.sha }}
-        DB_HOSTNAME: ${{ secrets.DB_HOSTNAME }}
-        DB_USERNAME: ${{ secrets.DB_USERNAME }}
-        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+        IMAGE_BUILD_OUTPUT=$(packer build -var 'artifact_path=${{ github.workspace }}/target/cloud-app-0.0.1-SNAPSHOT.jar' -var 'project_id=${{ env.PROJECT_ID }}' -var 'zone=${{ env.ZONE }}' cent.pkr.hcl)
+        echo "$IMAGE_BUILD_OUTPUT"
+        if echo "$IMAGE_BUILD_OUTPUT" | grep -q 'A disk image was created'; then
+          IMAGE_NAME=$(echo "$IMAGE_BUILD_OUTPUT" | grep 'A disk image was created' | awk -F': ' '{print $NF}')
+          echo "Image Name: $IMAGE_NAME"
+          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV
+        else
+          echo "Image build has failed or image ID wasn't found."
+          exit 1
+        fi
 
     - name: Create new Instance Template
       id: create_instance_template
       run: |
-          echo "Image created is: ${{steps.image_build.outputs.image_id}}"
-          gcloud compute instance-templates create ${{secrets.NEW_TEMPLATE_NAME}} \
-          --project=${{env.PROJECT_ID}} \
-          --instance-template-region=${{env.REGION}} \          
-          --network=${{env.NETWORK}} \
-          --subnet=${{env.SUBNET}} \
+          echo "Image created is: $IMAGE_NAME"
+          gcloud compute instance-templates create ${{ env.NEW_TEMPLATE_NAME }} \
+          --project=${{ env.PROJECT_ID }} \
+          --network=${{ env.NETWORK }} \
+          --subnet=${{ env.SUBNET }} \
           --boot-disk-type=pd-ssd \
-          --boot-disk-size=100 \
-          --boot-disk-auto-delete=true \
-          --tags=${{env.TAGS}} \
-          --region=${{env.REGION}} \
-          --machine-type=${{env.MACHINE_TYPE}} \
-          --image=projects/${{env.PROJECT_ID}}/global/images/${{steps.image_build.outputs.image_name}} \
-          --description= 'new template creation' \
-          --boot-disk-kms-key=${{secrets.KMS_KEY_SELF_LINK}} \
-          --metadata='startup-script= <<-EOF
-              #!/bin/bash
-
-              set -e
-
-              DB_HOSTNAME=${{env.DB_HOSTNAME}}
-              DB_PASSWORD=${{env.DB_PASSWORD}}
-
-              cat > /opt/.env <<EOF2
-              DB_HOSTNAME=${{env.DB_HOSTNAME}}
-              DB_USERNAME=webapp
-              DB_PASSWORD=${{env.DB_PASSWORD}}
-              EOF2
-
-              touch /var/run/startup-script-completed
-              EOF' \
-          --service-account=${{secrets.GCP_SERVICE_ACCOUNT_EMAIL}} \
-          --scopes=${{env.SCOPES}}
-          
-      
+          --boot-disk-size=100GB \
+          --boot-disk-auto-delete \
+          --tags=${{ env.TAGS }} \
+          --machine-type=${{ env.MACHINE_TYPE }} \
+          --image=projects/${{ env.PROJECT_ID }}/global/images/$IMAGE_NAME \
+          --description="New template creation" \
+          --boot-disk-kms-key=${{ env.KMS_KEY_SELF_LINK }} \
+          --metadata startup-script='#!/bin/bash
+          set -e
+          DB_HOSTNAME=${{ env.DB_HOSTNAME }}
+          DB_PASSWORD=${{ env.DB_PASSWORD }}
+          cat > /opt/.env <<EOF2
+          DB_HOSTNAME=${{ env.DB_HOSTNAME }}
+          DB_USERNAME=webapp
+          DB_PASSWORD=${{ env.DB_PASSWORD }}
+          EOF2
+          touch /var/run/startup-script-completed
+          ' \
+          --service-account=${{ env.GCP_SERVICE_ACCOUNT_EMAIL }} \
+          --scopes=${{ env.SCOPES }}
           echo "Initialised New Instance Template Variables" 
 
     - name: Update Managed Instance Group
       id: update_managed_instance_group
       run: |
-          gcloud compute instance-groups managed rolling-action start-update ${{env.INSTANCE_GROUP_NAME}} \
-          --version=template=https://compute.googleapis.com/compute/v1/projects/csye6225csye/global/instanceTemplates/${{secrets.NEW_TEMPLATE_NAME}} \
-          --region=${{env.REGION}}
+          gcloud compute instance-groups managed rolling-action start-update ${{ env.INSTANCE_GROUP_NAME }} \
+          --version=template=https://compute.googleapis.com/compute/v1/projects/csye6225csye/global/instanceTemplates/${{ secrets.NEW_TEMPLATE_NAME }} \
+          --region=${{ env.REGION }}
     - name: Wait for Managed Instance Group update
       id: wait_until_managed_instance_group_is_stable
       run: |
-          gcloud compute instance-groups managed wait-until ${{env.INSTANCE_GROUP_NAME}} \
+          gcloud compute instance-groups managed wait-until ${{ env.INSTANCE_GROUP_NAME }} \
           --version-target-reached \
-          --region=${{env.REGION}}
+          --region=${{ env.REGION }}
           echo "Managed Instance group is stable"
